framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\Message\CreatePerson: async

when@test:
    framework:
        messenger:
            transports:
                async: test://?catch_exceptions=false